# Generated by Django 3.2 on 2021-05-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('quizname', models.CharField(max_length=250)),
                ('quizdesc', models.CharField(max_length=500)),
                ('startdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('enddate', models.DateField()),
                ('endtime', models.TimeField()),
                ('quizstatus', models.BooleanField(default=False, editable=False)),
                ('creationdate', models.DateField()),
                ('creationtime', models.TimeField()),
                ('pubdate', models.DateField()),
                ('pubtime', models.TimeField()),
            ],
        ),
    ]
