# Generated by Django 3.2 on 2021-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
