# Generated by Django 3.2 on 2021-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0004_auto_20210517_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='responser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('clientip', models.CharField(max_length=250, null=True)),
                ('subdate', models.DateField()),
                ('subtime', models.TimeField()),
            ],
        ),
    ]
