# Generated by Django 3.2 on 2021-05-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0005_responser'),
    ]

    operations = [
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('quesid', models.PositiveIntegerField()),
                ('option', models.PositiveIntegerField()),
            ],
        ),
    ]
