# Generated by Django 3.2 on 2021-05-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0007_rename_response_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='responser',
            name='substatus',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
