# Generated by Django 3.2 on 2021-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0008_responser_substatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
